version: '3.8'
services:
  discoveryserver:
    build: discoveryserver
    image: discoveryserver
    ports:
    - "8761:8761"
    networks: {
      backend}
    restart: on-failure

  postcodesdistancecalculatorservice:
    build: postcodesdistancecalculatorservice
    image: postcodesdistancecalculatorservice
    deploy:
      replicas: 1
    ports:
    - "6567-6570:6567"
    networks: {
      backend}
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    restart: on-failure

  addressservice:
    build: addressservice
    image: addressservice
    deploy:
      replicas: 1
    ports:
    - "6571-6574:6565"
    networks: {
      backend}
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    restart: on-failure

  commissionservice:
    build: commissionservice
    image: commissionservice
    deploy:
      replicas: 1
    ports:
    - "6575-6578:6562"
    networks: {
      backend}
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    restart: on-failure

  demo:
    build: demo
    image: demo
    ports:
    - "8080:8080"
    networks: {
      backend}
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    restart: on-failure


  productsservice:
    build: productsservice
    image: productsservice
    deploy:
      replicas: 1
    ports:
    - "6588-6591:6564"
    networks: {
      backend}
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    restart: on-failure

  userservice:
    build: userservice
    image: userservice
    deploy:
      replicas: 1
    ports:
    - "6584-6587:6563"
    networks: {
      backend}
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discoveryserver:8761/eureka/
    restart: on-failure

networks:
    backend:
